# Generated by Django 4.1.3 on 2022-11-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default='lucin', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
