# Generated by Django 4.1.3 on 2022-11-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Ubacion'),
        ),
    ]
