# Generated by Django 4.1.3 on 2022-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=900, verbose_name='Descripcion'),
        ),
    ]
